# config.yaml

data_dir: sra_data

subdirs:
  lists: sra_lists
  output: sra_files
  logs: logs
  fastq: fastq_files
  split_fastq: split_fastq_files
  barcodes: barcode_dir
  star: star

logs:
  csv: csv_logs
  python: python_logs
  split: split_logs

star:
  genome_dir: genome_ref
  star_output: star_output

demux:
  output_subdir: split_fastq_files  # â† reuses what's in subdirs
  entrez_email: your@gmail.com
  gsm_cache: gsm_cache.json